#include "Moose.h"
#include "MarmotApp.h"
#include "Factory.h"
#include "AppFactory.h"
#include "ActionFactory.h"

/**
 * Module Includes
 */
#include "HeatConductionApp.h"
#include "MiscApp.h"
#include "PhaseFieldApp.h"
#ifdef MAGPIE_ENABLED
#  include "MagpieApp.h"
#endif
#include "TensorMechanicsApp.h"

#include "MarmotSyntax.h"
#include "MarmotRevision.h" // This file is autogenerated and contains the revision.

/**
 * Kernels
 */
#include "ACBulkZrH.h"
#include "ACFracBulkRate.h"
#include "ACFracCoupledInterface.h"
#include "ACFracIntVar.h"
#include "ACGrBuPoly.h"
#include "ACGrGrGenericDF.h"
#include "ACGrGrTensorCrystPlasticDF.h"
#include "ACGrGrTGrad.h"
#include "ACOPwVacGas.h"
#include "ACPoreGBPurdue.h"
#include "AlgebraDebug.h"
#include "CGp.h"
#include "CHGaswVac.h"
#include "CHGBPoly.h"
#include "CHGrBu.h"
#include "CHInterface2.h"
#include "CHInterface3.h"
#include "CHInterface4.h"
#include "CHInterfaceMMS.h"
#include "CHInterfaceSplit.h"
#include "CHPhys.h"
#include "CHRadSink.h"
#include "CHRadSinkAniso.h"
#include "CHRadSinkAnisoUI.h"
#include "CHRadSinkAnisoVa.h"
#include "CHRadSinkAnisoVaVa.h"
#include "CHRadSinkAnisoXe.h"
#include "CHRadSinkAnisoXeE.h"
#include "CHRadSinkAnisoXeVa_1.h"
#include "CHRadSinkAnisoXeVa_2.h"
#include "CHRadSinkAnisoXeVa_3.h"
#include "CHTGrad.h"
#include "CHVacGB.h"
#include "CHVacwGas.h"
#include "CoupleStressDivTensors.h"
#include "CVap.h"
#include "FeCrCHBulk.h"
#include "FissionGasCoupledLinear.h"
#include "FissionGasLinear.h"
#include "FissionGasSource.h"
#include "GammaZrHElasticEnergy.h"
#include "MaterialPropertyValue.h"
#include "OrderParamInterface.h"
#include "RadSourcePoly.h"
#include "RadSourceVExp.h"
#include "SplitCHBeta.h"
#include "SplitCHEigenStrain.h"
#include "SplitCHGBPoly.h"
#include "SplitCHLinearElasticity.h"
#include "SplitCHPhys.h"
#include "SplitCHPoreGB.h"
#include "SplitCHPoreGBPurdue.h"
#include "SplitCHTwoComp.h"
#include "SplitCHWResGBSurfDiff.h"
#include "SplitCHWResMtrxMob.h"
#include "SplitCHWResTGrad.h"
#include "SplitCHZrH.h"
#include "StressDivergenceTensorsPFFrac.h"
#include "UI_XeVa2UIRate.h"
#include "UIDiffusion.h"
#include "UISinkRate.h"
#include "UISinkRateGB.h"
#include "UISource.h"
#include "UIVa2Rate.h"
#include "UIVaRate.h"
#include "UIXeVaRate.h"
#include "Va_Va2UIRate.h"
#include "Va_VaVaRate.h"
#include "Va_XeVa2BRate.h"
#include "Va_XeVa2Rate.h"
#include "Va_XeVaRate.h"
#include "Va_XeXeVaRate.h"
#include "Va2_XeVa2_BRate.h"
#include "Va2_XeVa2MRate.h"
#include "Va2_XeVa2Rate.h"
#include "Va2SinkRate.h"
#include "Va2SinkRateGB.h"
#include "Va2UIRate.h"
#include "VaDiffusion.h"
#include "VaSinkRate.h"
#include "VaSinkRateGB.h"
#include "VaSource.h"
#include "VaUIRate.h"
#include "VaVaDiffusion.h"
#include "VaVaRate.h"
#include "Xe_XeVa2_BRate.h"
#include "Xe_XeVa2MRate.h"
#include "Xe_XeVa2Rate.h"
#include "Xe_XeVaRate.h"
#include "Xe_XeVaUIRate.h"
#include "Xe_XeXeVaRate.h"
#include "XeDiffusion.h"
#include "XeEDiffusion.h"
#include "XeSinkRate.h"
#include "XeVa_XeVa2BRate.h"
#include "XeVa_XeVa2UIRate.h"
#include "XeVa_XeVaXeVaRate.h"
#include "XeVa2_BRate.h"
#include "XeVa2_XeVa2BRate.h"
#include "XeVa2_XeVa2MRate.h"
#include "XeVa2_XeXeVaRate.h"
#include "XeVa2Diffusion.h"
#include "XeVa2Rate.h"
#include "XeVa2UIRate.h"
#include "XeVaDiffusion.h"
#include "XeVaRate.h"
#include "XeVaUIRate.h"
#include "XeVaXeVaRate.h"
#include "XeXeVaDiffusion.h"
#include "XeXeVaRate.h"

/**
 * Auxiliary Kernels
 */
#include "CgBTOTAux.h"
#include "CgTOT3Aux.h"
#include "CgTOT4Aux.h"
#include "CgTOTAux.h"
#include "ConcentrationAux.h"
#include "CuTOT3Aux.h"
#include "CuTOTAux.h"
#include "Euler2RGBAux.h"
#include "FeCrFreeEnergyCalculation.h"
#include "FlowAux.h"
#include "GBCalcAux.h"
#include "GrainOrientation.h"
#include "MaxShear.h"
#include "PoreGBFreeEnergyCalculation.h"
#include "PoreGBPurdueFreeEnergyCalc.h"
#include "RankTwoEigenvals.h"
#include "ReconAuxVarUpdate.h"
#include "TestEBSDAux.h"
#include "TimeDerivativeAux.h"
#include "VaAux.h"
#include "ZrHFreeEnergy.h"

/**
 * Dirac Kernels
 */
#include "RandomPointSource.h"

/**
 * Boundary Conditions
 */
#include "ACGrGrIntegratedBC.h"
#include "CHFunctionBC.h"
#include "CHRadPenaltyBC.h"

/**
 * Materials
 */
#include "AnisotropicEigenStrainMaterial.h"
#include "CalphadAB1CD1Material.h"
#include "CalphadAB1CD2Material.h"
#include "CDDFSPlasticMaterial.h"
#include "CDDFSPlasticStrainGradMaterial.h"
#include "ConcEvolution.h"
#include "CoupledPFCrysPlastMaterial.h"
#include "CTempIrrad.h"
#include "CuGrGr.h"
#include "CuVacProps.h"
#include "EigenStrainFracMaterial.h"
#include "FiniteStrainElasticPFDamage.h"
#include "FractureACBulkMatRate.h"
#include "FractureACBulkMatRateSolIC.h"
#include "FractureACInterfaceMatRate.h"
#include "GammaZrHMaterial.h"
#include "GeneralGrBu.h"
#include "GenericMaterialMaterial.h"
#include "GenIrrad.h"
#include "LinearElasticPFDamage.h"
#include "LinearElasticPFDamageJintegral.h"
#include "LinearElasticPFDamagePorosity.h"
#include "LinearElasticPFDamageSolIC.h"
#include "MesoUO2.h"
#include "MicroThermal.h"
#include "MicroThermalUO2XeT.h"
#include "NeutronSrc.h"
#include "PoreGBMaterial.h"
#include "PoreGBMtrxMobMaterial.h"
#include "PoreGBPurdueMaterial.h"
#include "ReconMaterial.h"
#include "ThCondMOX.h"
#include "ThCondSimpleMOX.h"
#include "UO2AnisoConsTemp.h"
#include "UO2AnisoConsTempXe.h"
#include "UO2AnisoConsTempXeL.h"
#include "UO2AnisoConsTempXeUVa.h"
#include "UO2AnisoConsTempXeUVa2.h"
#include "UO2AnisoConsTempXeUVa2Xe.h"
#include "UO2AnisoConsTempXeUVaB.h"
#include "UO2GrGr.h"
#include "UO2VacGas.h"
#include "UO2VacGBConsT.h"
#include "VarTempIrrad.h"
#include "VoidTempGrad.h"
#include "ZrHTransStrainMaterial.h"

/**
 * Initial Conditions
 */
#include "BubblesBicrystalIC.h"
#include "CHMMSIC.h"
#include "CircleGrainVoidIC.h"
#include "MultiBoundingBoxIC.h"
#include "MultiSmoothCirclePorosityIC.h"
#include "PerturbedCylinderIC.h"
#include "PlanarSmoothCircleIC.h"
#include "PolycrystalVoidIC.h"
#include "PolycrystalVoronoiVoidIC.h"
#include "Recon2RGBIC.h"
#include "ReconAuxVarIC.h"
#include "SinusoidalSurfaceIC.h"

/**
 * Dampers
 */

/**
 * Executioners
 */

/**
 * Post Processors
 */
#include "CalculateGasOnGB.h"
#include "DiffusivityBox.h"
#include "EffectiveKapitzaResistance.h"
#include "FeCrInt_energy.h"
#include "GBPosition.h"
#include "GrainBoundaryBubbleCoverage.h"
#include "MidPlaneBubbleCoverage.h"
#include "NodePosition.h"
#include "OneBubbleGBC.h"
#include "PolycrystalAvEulerAngle.h"
#include "PolycrystalAvGrArea.h"
#include "Porosity.h"
#include "SplitCHCRes.h"

template<>
InputParameters validParams<MarmotApp>()
{
  InputParameters params = validParams<MooseApp>();

  params.set<bool>("use_legacy_uo_initialization") = false;
  params.set<bool>("use_legacy_uo_aux_computation") = false;
  return params;
}

MarmotApp::MarmotApp(InputParameters parameters) :
    MooseApp(parameters)
{
  Moose::registerObjects(_factory);

  PhaseFieldApp::registerObjects(_factory);
  TensorMechanicsApp::registerObjects(_factory);
  HeatConductionApp::registerObjects(_factory);
  MiscApp::registerObjects(_factory);

#ifdef MAGPIE_ENABLED
  MagpieApp::registerObjects(_factory);
#endif

  MarmotApp::registerObjects(_factory);

  Moose::associateSyntax(_syntax, _action_factory);

  PhaseFieldApp::associateSyntax(_syntax, _action_factory);
  TensorMechanicsApp::associateSyntax(_syntax, _action_factory);
  HeatConductionApp::associateSyntax(_syntax, _action_factory);
  MiscApp::associateSyntax(_syntax, _action_factory);

#ifdef MAGPIE_ENABLED
  MagpieApp::associateSyntax(_syntax, _action_factory);
#endif

  Marmot::associateSyntax(_syntax, _action_factory);
}

// External entry point for dynamic application loading
extern "C" void MarmotApp__registerApps() { MarmotApp::registerApps(); }
void
MarmotApp::registerApps()
{
#undef  registerApp
#define registerApp(name) AppFactory::instance().reg<name>(#name)

  registerApp(MarmotApp);

#undef  registerApp
#define registerApp(name) AppFactory::instance().regLegacy<name>(#name)
}

// External entry point for dynamic object registration
extern "C" void MarmotApp__registerObjects(Factory & factory) { MarmotApp::registerObjects(factory); }
void
MarmotApp::registerObjects(Factory & factory)
{
#undef registerObject
#define registerObject(name) factory.reg<name>(stringifyName(name))

  /**
   * Kernels
   */
  registerKernel(ACBulkZrH);
  registerKernel(ACFracBulkRate);
  registerKernel(ACFracCoupledInterface);
  registerKernel(ACFracIntVar);
  registerKernel(ACGrBuPoly);
  registerKernel(ACGrGrGenericDF);
  registerKernel(ACGrGrTensorCrystPlasticDF);
  registerKernel(ACGrGrTGrad);
  registerKernel(ACOPwVacGas);
  registerKernel(ACPoreGBPurdue);
  registerKernel(AlgebraDebug);
  registerKernel(CGp);
  registerKernel(CHGaswVac);
  registerKernel(CHGBPoly);
  registerKernel(CHGrBu);
  registerKernel(CHInterface2);
  registerKernel(CHInterface3);
  registerKernel(CHInterface4);
  registerKernel(CHInterfaceMMS);
  registerKernel(CHInterfaceSplit);
  registerKernel(CHPhys);
  registerKernel(CHRadSink);
  registerKernel(CHRadSinkAniso);
  registerKernel(CHRadSinkAnisoUI);
  registerKernel(CHRadSinkAnisoVa);
  registerKernel(CHRadSinkAnisoVaVa);
  registerKernel(CHRadSinkAnisoXe);
  registerKernel(CHRadSinkAnisoXeE);
  registerKernel(CHRadSinkAnisoXeVa_1);
  registerKernel(CHRadSinkAnisoXeVa_2);
  registerKernel(CHRadSinkAnisoXeVa_3);
  registerKernel(CHTGrad);
  registerKernel(CHVacGB);
  registerKernel(CHVacwGas);
  registerKernel(CoupleStressDivTensors);
  registerKernel(CVap);
  registerKernel(FeCrCHBulk);
  registerKernel(FissionGasCoupledLinear);
  registerKernel(FissionGasLinear);
  registerKernel(FissionGasSource);
  registerKernel(GammaZrHElasticEnergy);
  registerKernel(MaterialPropertyValue);
  registerKernel(OrderParamInterface);
  registerKernel(RadSourcePoly);
  registerKernel(RadSourceVExp);
  registerKernel(SplitCHBeta);
  registerKernel(SplitCHEigenStrain);
  registerKernel(SplitCHGBPoly);
  registerKernel(SplitCHLinearElasticity);
  registerKernel(SplitCHPhys);
  registerKernel(SplitCHPoreGB);
  registerKernel(SplitCHPoreGBPurdue);
  registerKernel(SplitCHTwoComp);
  registerKernel(SplitCHWResGBSurfDiff);
  registerKernel(SplitCHWResMtrxMob);
  registerKernel(SplitCHWResTGrad);
  registerKernel(SplitCHZrH);
  registerKernel(StressDivergenceTensorsPFFrac);
  registerKernel(UI_XeVa2UIRate);
  registerKernel(UIDiffusion);
  registerKernel(UISinkRate);
  registerKernel(UISinkRateGB);
  registerKernel(UISource);
  registerKernel(UIVa2Rate);
  registerKernel(UIVaRate);
  registerKernel(UIXeVaRate);
  registerKernel(Va_Va2UIRate);
  registerKernel(Va_VaVaRate);
  registerKernel(Va_XeVa2BRate);
  registerKernel(Va_XeVa2Rate);
  registerKernel(Va_XeVaRate);
  registerKernel(Va_XeXeVaRate);
  registerKernel(Va2_XeVa2_BRate);
  registerKernel(Va2_XeVa2MRate);
  registerKernel(Va2_XeVa2Rate);
  registerKernel(Va2SinkRate);
  registerKernel(Va2SinkRateGB);
  registerKernel(Va2UIRate);
  registerKernel(VaDiffusion);
  registerKernel(VaSinkRate);
  registerKernel(VaSinkRateGB);
  registerKernel(VaSource);
  registerKernel(VaUIRate);
  registerKernel(VaVaDiffusion);
  registerKernel(VaVaRate);
  registerKernel(Xe_XeVa2_BRate);
  registerKernel(Xe_XeVa2MRate);
  registerKernel(Xe_XeVa2Rate);
  registerKernel(Xe_XeVaRate);
  registerKernel(Xe_XeVaUIRate);
  registerKernel(Xe_XeXeVaRate);
  registerKernel(XeDiffusion);
  registerKernel(XeEDiffusion);
  registerKernel(XeSinkRate);
  registerKernel(XeVa_XeVa2BRate);
  registerKernel(XeVa_XeVa2UIRate);
  registerKernel(XeVa_XeVaXeVaRate);
  registerKernel(XeVa2_BRate);
  registerKernel(XeVa2_XeVa2BRate);
  registerKernel(XeVa2_XeVa2MRate);
  registerKernel(XeVa2_XeXeVaRate);
  registerKernel(XeVa2Diffusion);
  registerKernel(XeVa2Rate);
  registerKernel(XeVa2UIRate);
  registerKernel(XeVaDiffusion);
  registerKernel(XeVaRate);
  registerKernel(XeVaUIRate);
  registerKernel(XeVaXeVaRate);
  registerKernel(XeXeVaDiffusion);
  registerKernel(XeXeVaRate);
  // registerKernel(ACGBPoly);
  // registerKernel(ACGrGrPolyGrTracker);

  /**
   * Auxiliary Kernels
   */
  registerAux(CgBTOTAux);
  registerAux(CgTOT3Aux);
  registerAux(CgTOT4Aux);
  registerAux(CgTOTAux);
  registerAux(ConcentrationAux);
  registerAux(CuTOT3Aux);
  registerAux(CuTOTAux);
  registerAux(Euler2RGBAux);
  registerAux(FeCrFreeEnergyCalculation);
  registerAux(FlowAux);
  registerAux(GBCalcAux);
  registerAux(GrainOrientation);
  registerAux(MaxShear);
  registerAux(PoreGBFreeEnergyCalculation);
  registerAux(PoreGBPurdueFreeEnergyCalc);
  registerAux(RankTwoEigenvals);
  registerAux(ReconAuxVarUpdate);
  registerAux(TestEBSDAux);
  registerAux(TimeDerivativeAux);
  registerAux(VaAux);
  registerAux(ZrHFreeEnergy);

  /**
   * Dirac Kernels
   */
  registerDiracKernel(RandomPointSource);

  /**
   * Boundary Conditions
   */
  registerBoundaryCondition(ACGrGrIntegratedBC);
  registerBoundaryCondition(CHFunctionBC);
  registerBoundaryCondition(CHRadPenaltyBC);

  /**
   * Materials
   */
  registerMaterial(AnisotropicEigenStrainMaterial);
  registerMaterial(CalphadAB1CD1Material);
  registerMaterial(CalphadAB1CD2Material);
  registerMaterial(CDDFSPlasticMaterial);
  registerMaterial(CDDFSPlasticStrainGradMaterial);
  registerMaterial(ConcEvolution);
  registerMaterial(CoupledPFCrysPlastMaterial);
  registerMaterial(CTempIrrad);
  registerMaterial(CuGrGr);
  registerMaterial(CuVacProps);
  registerMaterial(EigenStrainFracMaterial);
  registerMaterial(FiniteStrainElasticPFDamage);
  registerMaterial(FractureACBulkMatRate);
  registerMaterial(FractureACBulkMatRateSolIC);
  registerMaterial(FractureACInterfaceMatRate);
  registerMaterial(GammaZrHMaterial);
  registerMaterial(GeneralGrBu);
  registerMaterial(GenericMaterialMaterial);
  registerMaterial(GenIrrad);
  registerMaterial(LinearElasticPFDamage);
  registerMaterial(LinearElasticPFDamageJintegral);
  registerMaterial(LinearElasticPFDamagePorosity);
  registerMaterial(LinearElasticPFDamageSolIC);
  registerMaterial(MesoUO2);
  registerMaterial(MicroThermal);
  registerMaterial(MicroThermalUO2XeT);
  registerMaterial(NeutronSrc);
  registerMaterial(PoreGBMaterial);
  registerMaterial(PoreGBMtrxMobMaterial);
  registerMaterial(PoreGBPurdueMaterial);
  registerMaterial(ReconMaterial);
  registerMaterial(ThCondMOX);
  registerMaterial(ThCondSimpleMOX);
  registerMaterial(UO2AnisoConsTemp);
  registerMaterial(UO2AnisoConsTempXe);
  registerMaterial(UO2AnisoConsTempXeL);
  registerMaterial(UO2AnisoConsTempXeUVa);
  registerMaterial(UO2AnisoConsTempXeUVa2);
  registerMaterial(UO2AnisoConsTempXeUVa2Xe);
  registerMaterial(UO2AnisoConsTempXeUVaB);
  registerMaterial(UO2GrGr);
  registerMaterial(UO2VacGas);
  registerMaterial(UO2VacGBConsT);
  registerMaterial(VarTempIrrad);
  registerMaterial(VoidTempGrad);
  registerMaterial(ZrHTransStrainMaterial);

  /**
   * Initial Conditions
   */
  registerInitialCondition(BubblesBicrystalIC);
  registerInitialCondition(CHMMSIC);
  registerInitialCondition(CircleGrainVoidIC);
  registerInitialCondition(MultiBoundingBoxIC);
  registerInitialCondition(MultiSmoothCirclePorosityIC);
  registerInitialCondition(PerturbedCylinderIC);
  registerInitialCondition(PlanarSmoothCircleIC);
  registerInitialCondition(PolycrystalVoidIC);
  registerInitialCondition(PolycrystalVoronoiVoidIC);
  registerInitialCondition(Recon2RGBIC);
  registerInitialCondition(ReconAuxVarIC);
  registerInitialCondition(SinusoidalSurfaceIC);

  /**
   * Dampers
   */

  /**
   * Executioners
   */

  /**
   * Post Processors
   */
  registerPostprocessor(CalculateGasOnGB);
  registerPostprocessor(DiffusivityBox);
  registerPostprocessor(EffectiveKapitzaResistance);
  registerPostprocessor(FeCrInt_energy);
  registerPostprocessor(GBPosition);
  registerPostprocessor(GrainBoundaryBubbleCoverage);
  registerPostprocessor(MidPlaneBubbleCoverage);
  registerPostprocessor(NodePosition);
  registerPostprocessor(OneBubbleGBC);
  registerPostprocessor(PolycrystalAvEulerAngle);
  registerPostprocessor(PolycrystalAvGrArea);
  registerPostprocessor(Porosity);
  registerPostprocessor(SplitCHCRes);

#undef registerObject
#define registerObject(name) factory.regLegacy<name>(stringifyName(name))
}

void
MarmotApp::runInputFile()
{
  printHeader();
  MooseApp::runInputFile();
}

void
MarmotApp::printHeader()
{
  Moose::out << "\n"
             << "\n"
             << "     Prepared by Battelle Energy Alliance, LLC\n"
             << "        Under Contract No. DE-AC07-05ID14517\n"
             << "        With the U. S. Department of Energy\n"
             << "\n"
             << "\n";

  Moose::out <<
"-----------------------------------------------------------------------------\n"
"NOTICE:  This computer software was prepared by Battelle Energy Alliance, LLC,\n"
"hereinafter the Contractor, under Contract No. DE-AC07-05ID14517 with the\n"
"United States (U.S.) Department of Energy (DOE).  All rights in the computer\n"
"software are reserved by DOE on behalf of the United States Government and, if\n"
"applicable, the Contractor as provided in the Contract. You are authorized to\n"
"use this computer software for Governmental purposes but it is not to be\n"
"released or distributed to the public.  NEITHER THE UNITED STATES GOVERNMENT,\n"
"NOR DOE, NOR THE CONTRACTOR MAKE ANY WARRANTY, EXPRESSED OR IMPLIED, OR ASSUMES\n"
"ANY LIABILITY OR RESPONSIBILITY FOR THE USE, ACCURACY, COMPLETENESS, OR\n"
"USEFULNESS OR ANY INFORMATION, APPARATUS, PRODUCT, OR PROCESS DISCLOSED, OR\n"
"REPRESENTS THAT ITS USE WOULD NOT INFRINGE PRIVATELY OWNED RIGHTS.  This notice,\n"
"including this sentence, must appear on any copies of this computer software.\n"
"\n"
"EXPORT RESTRICTIONS. The provider of this computer software and its employees\n"
"and its agents are subject to U.S. export control laws that prohibit or restrict\n"
"(i) transactions with certain parties, and (ii) the type and level of\n"
"technologies and services that may be exported.  You agree to comply fully with\n"
"all laws and regulations of the United States and other countries (Export Laws)\n"
"to assure that neither this computer software, nor any direct products thereof\n"
"are (1) exported, directly or indirectly, in violation of Export Laws, or (2)\n"
"are used for any purpose prohibited by Export Laws, including, without\n"
"limitation, nuclear, chemical, or biological weapons proliferation.\n"
"\n"
"None of this computer software or underlying information or technology may be\n"
"downloaded or otherwise exported or re-exported (i) into (or to a national or\n"
"resident of) Cuba, North Korea, Iran, Sudan, Syria or any other country to which\n"
"the U.S. has embargoed goods; or (ii) to anyone on the U.S. Treasury\n"
"Department's List of Specially Designated Nationals or the U.S. Commerce\n"
"Department's Denied Persons List, Unverified List, Entity List, Nonproliferation\n"
"Sanctions or General Orders.  By downloading or using this computer software,\n"
"you are agreeing to the foregoing and you are representing and warranting that\n"
"you are not located in, under the control of, or a national or resident of any\n"
"such country or on any such list, and that you acknowledge you are responsible\n"
"to obtain any necessary U.S. government authorization to ensure compliance with\n"
"U.S. law.\n"
"\n"
"THE PROVIDER OF THIS SOFTWARE SPECIFICALLY DISCLAIMS ANY AND ALL EXPRESS OR\n"
"IMPLIED WARRANTIES INCLUDING, WITHOUT LIMITATION, ANY AND ALL WARRANTIES OF\n"
"MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. THE COMPUTER SOFTWARE\n"
"IS PROVIDED \"AS IS.\"\n"
"-----------------------------------------------------------------------------\n"
"\n";

  Moose::out << std::left;
  Moose::out << std::setw(25) << "Marmot version: " << MARMOT_REVISION << "\n\n";
}
