#include "AvEulerAnglePostprocessorAction.h"
#include "Factory.h"
#include "Parser.h"
#include "FEProblem.h"

template<>
InputParameters validParams<AvEulerAnglePostprocessorAction>()
{
  InputParameters params = validParams<Action>();
  params.addRequiredCoupledVar("v", "Array of coupled variables");
  params.addRequiredParam<unsigned int>("op_num", "specifies the number of grains to create");
  params.addRequiredParam<std::string>("var_name_base", "specifies the base name of the variables");
  MultiMooseEnum execute_options(SetupInterface::getExecuteOptions());
  params.addRequiredParam<MultiMooseEnum>("execute_on", execute_options, "execute_on options for the PostProcessors generated by this action");
  return params;
}

AvEulerAnglePostprocessorAction::AvEulerAnglePostprocessorAction(const InputParameters & params) :
    Action(params),
    _op_num(getParam<unsigned int>("op_num")),
    _var_name_base(getParam<std::string>("var_name_base")),
    _execute_on(getParam<MultiMooseEnum>("execute_on"))
{
}

void
AvEulerAnglePostprocessorAction::act()
{
#ifdef DEBUG
  Moose::err << "Inside the AvEulerAnglePostprocessorAction Object\n";
  Moose::err << "var name base:" << _var_name_base;
#endif

  for (unsigned int op = 0; op < _op_num; ++op)
    for (unsigned int angle = 1; angle < 4; ++angle)
    {
      // Create variable names
      std::string var_name = _var_name_base;
      std::string angle_name = "angle_number";

      std::stringstream out;
      std::stringstream number;

      out << op;
      number << angle;

      var_name.append(out.str());
      angle_name.append(number.str());

      InputParameters poly_params = _factory.getValidParams("PolycrystalAvEulerAngle");

      poly_params.set<std::vector<VariableName> >("v") = getParam<std::vector<VariableName> >("v");
      poly_params.set<unsigned int>("grain_number") = op;
      poly_params.set<unsigned int>("angle_number") = angle;
      poly_params.set<MultiMooseEnum>("execute_on") = _execute_on;

      std::string post_processor_name = var_name;
      post_processor_name.append(angle_name);

      _problem->addPostprocessor("PolycrystalAvEulerAngle", post_processor_name, poly_params);
    }
}
